export const NO_DATA_FOUND = 'No data to visualize!';
export const LEGEND_PERCENTAGE = 'PercentageLegend';
export const DEFAULT_BARGRAPH_ORIENTATION = 'vertical';
export const X_AXIS_HEIGHT = 50;
export const PERCENTAGE = 'percentage';
export const LEGEND_SEPARATE = 20;
export const BRUSH_HEIGHT = 20;
export const XLABEL_HEIGHT = 20;
export const RADIAN = Math.PI / 180;